# Generated by Django 5.0.3 on 2024-04-13 14:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='malumot')),
            ],
            options={
                'verbose_name': 'ish malumot ',
                'verbose_name_plural': 'ish malumotlar',
            },
        ),
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='sarlavha')),
                ('desciption', models.CharField(max_length=75, verbose_name='tarif')),
                ('text', models.TextField(verbose_name='malumot')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'biz haqimizda',
                'verbose_name_plural': 'biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='sarlavfa')),
                ('desciption', models.CharField(max_length=255, verbose_name='tarif')),
                ('icon', models.ImageField(upload_to='advantage_icon', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Afzallik',
                'verbose_name_plural': 'Afzalliklar',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='sarlavha')),
                ('desciption', models.CharField(max_length=255, verbose_name='tarif')),
                ('image', models.ImageField(upload_to='banner_photo', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Bosh sahifa',
                'verbose_name_plural': 'Bosh sahifalar',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='nomi')),
                ('address', models.CharField(max_length=255, verbose_name='manzil')),
                ('start_time', models.TimeField(verbose_name='boshlanish vaqt')),
                ('end_time', models.TimeField(verbose_name='tugash vaqt')),
                ('lat', models.FloatField()),
                ('lot', models.FloatField()),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=75, verbose_name='ism familiya')),
                ('bio', models.TextField(verbose_name="o'zi haqida malumot")),
                ('image', models.ImageField(upload_to='career_photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'karyera',
                'verbose_name_plural': 'karyeralar',
            },
        ),
        migrations.CreateModel(
            name='Conact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, verbose_name='telefon raqam')),
                ('extra_number', models.CharField(max_length=13, verbose_name='yetgazib beruvchi telefon raqami')),
                ('ofis_address', models.CharField(max_length=75, verbose_name='mazil ofis')),
            ],
            options={
                'verbose_name': 'kontak',
                'verbose_name_plural': 'kontaklar',
            },
        ),
        migrations.CreateModel(
            name='Favorite_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(max_length=255, verbose_name='tarif')),
                ('icon', models.ImageField(upload_to='favorite_food/', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume_photo/', verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=255, verbose_name='telegram')),
                ('instagram', models.CharField(max_length=255, verbose_name='instagram')),
                ('facebook', models.CharField(max_length=255, verbose_name='facebook')),
                ('play_market', models.CharField(max_length=255, verbose_name='play_market')),
                ('app_store', models.CharField(max_length=255, verbose_name='app_store')),
                ('banner_logo', models.ImageField(upload_to='banner_logo/', verbose_name='banner_logo')),
                ('banner_photo', models.ImageField(upload_to='banner_photo/', verbose_name='banner_photo')),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infolar',
            },
        ),
        migrations.CreateModel(
            name='Job_benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='toliq malomot')),
                ('icon', models.ImageField(upload_to='job_benefit_icon/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'ish avfzalik',
                'verbose_name_plural': 'ish avfzaliklari',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='sarlavha')),
                ('text', models.TextField(verbose_name='malumot')),
                ('image', models.ImageField(upload_to='new_photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='nomi')),
                ('desciption', models.CharField(max_length=75, verbose_name='tarif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='naxri')),
                ('image', models.ImageField(upload_to='product_photo', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Send_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='ism va falimiya')),
                ('phone_number', models.CharField(max_length=13, verbose_name='telefon raqam')),
                ('image', models.ImageField(upload_to='send_request_photo')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='teg')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullame', models.CharField(max_length=55, verbose_name='ism familiya')),
                ('comment', models.TextField(verbose_name='komentariya')),
                ('type', models.CharField(choices=[('telegram', 'telegram'), ('facebook', 'facebook'), ('instagram', 'instagram')], max_length=25)),
            ],
            options={
                'verbose_name': 'izoh',
                'verbose_name_plural': 'izohlar',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='sarlavfa')),
                ('text', models.TextField(verbose_name="to'liq malumot")),
                ('desciption', models.CharField(max_length=75, verbose_name='tarif')),
            ],
            options={
                'verbose_name': 'Ish haqida malomut',
                'verbose_name_plural': 'Ishlar haqida malomut',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='saravha')),
                ('text', models.TextField(verbose_name='malumot')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image', verbose_name='rasm tanlash')),
            ],
            options={
                'verbose_name': 'rasm',
                'verbose_name_plural': 'rasmlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag', verbose_name='teg'),
        ),
    ]
