# Generated by Django 5.0.2 on 2024-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conact',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='product',
            name='retsept',
            field=models.TextField(default=1, verbose_name='tarif'),
            preserve_default=False,
        ),
    ]
