# Generated by Django 5.0.2 on 2024-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket_quantity'),
        ('main', '0002_rename_conact_contact_product_retsept'),
    ]

    operations = [
    ]
